package com.example.coursesapp

import com.example.coursesapp.model.Topic

object DataSource {
    val topics = listOf(
        Topic(topicId = R.string.architecture, 58, R.drawable.architecture),
        Topic(topicId = R.string.crafts, 121, R.drawable.crafts),
        Topic(topicId = R.string.business, 78, R.drawable.business),
        Topic(topicId = R.string.culinary, 118, R.drawable.culinary),
        Topic(topicId = R.string.design, 423, R.drawable.design),
        Topic(topicId = R.string.fashion, 92, R.drawable.fashion),
        Topic(topicId = R.string.film, 165, R.drawable.film),
        Topic(topicId = R.string.gaming, 164, R.drawable.gaming),
        Topic(topicId = R.string.drawing, 326, R.drawable.drawing),
        Topic(topicId = R.string.lifestyle, 305, R.drawable.lifestyle),
        Topic(topicId = R.string.music, 212, R.drawable.music),
        Topic(topicId = R.string.painting, 172, R.drawable.painting),
        Topic(topicId = R.string.photography, 321, R.drawable.photography),
        Topic(topicId = R.string.tech, 118, R.drawable.tech),
        Topic(topicId = R.string.biology, 45, R.drawable.biology),
        Topic(topicId = R.string.automotive, 521, R.drawable.automotive),
        Topic(topicId = R.string.ecology, 89, R.drawable.ecology),
        Topic(topicId = R.string.engineering, 67, R.drawable.engineering),
        Topic(topicId = R.string.finance, 145, R.drawable.finance),
        Topic(topicId = R.string.geology, 217, R.drawable.geology),
        Topic(topicId = R.string.history, 61, R.drawable.history),
        Topic(topicId = R.string.journalism, 145, R.drawable.journalism),
        Topic(topicId = R.string.law, 217, R.drawable.law),
        Topic(topicId = R.string.physics, 61, R.drawable.physics),
        Topic(topicId = R.string.architecture, 58, R.drawable.architecture),
        Topic(topicId = R.string.crafts, 121, R.drawable.crafts),
        Topic(topicId = R.string.business, 78, R.drawable.business),
        Topic(topicId = R.string.culinary, 118, R.drawable.culinary),
        Topic(topicId = R.string.design, 423, R.drawable.design),
        Topic(topicId = R.string.fashion, 92, R.drawable.fashion),
        Topic(topicId = R.string.film, 165, R.drawable.film),
        Topic(topicId = R.string.gaming, 164, R.drawable.gaming),
        Topic(topicId = R.string.drawing, 326, R.drawable.drawing),
        Topic(topicId = R.string.lifestyle, 305, R.drawable.lifestyle),
        Topic(topicId = R.string.music, 212, R.drawable.music),
        Topic(topicId = R.string.painting, 172, R.drawable.painting),
        Topic(topicId = R.string.photography, 321, R.drawable.photography),
        Topic(topicId = R.string.tech, 118, R.drawable.tech),
        Topic(topicId = R.string.biology, 45, R.drawable.biology),
        Topic(topicId = R.string.automotive, 521, R.drawable.automotive),
        Topic(topicId = R.string.ecology, 89, R.drawable.ecology),
        Topic(topicId = R.string.engineering, 67, R.drawable.engineering),
        Topic(topicId = R.string.finance, 145, R.drawable.finance),
        Topic(topicId = R.string.geology, 217, R.drawable.geology),
        Topic(topicId = R.string.history, 61, R.drawable.history),
        Topic(topicId = R.string.journalism, 145, R.drawable.journalism),
        Topic(topicId = R.string.law, 217, R.drawable.law),
        Topic(topicId = R.string.physics, 61, R.drawable.physics),
    )
}